---
- name: update files
  hosts: k8s_master
  become: yes 
 
  tasks: 
    - name: copy file 
      copy: 
        src: ./ 
        dest: ~/jenkins/
 
    - name: docker build 
      shell: docker build -t wlsthq531jpn/testweb:6.0 ~/jenkins/ 
 
    - name: docker push 
      shell: docker push wlsthq531jpn/testweb:6.0 
 
    - name: kubernetes create 
      shell: kubectl apply -f ~/jenkins/httpd.yaml  

